[package]
name = "ere-hosts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = []

[dependencies]
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

benchmark-runner.workspace = true
zkvm-interface.workspace = true

# Optional dependencies based on features
ere-dockerized = { workspace = true }

[lints]
workspace = true
