name: Release Compiled Guests

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write

env:
  ERE_TAG: 0.0.15-d15d36a

jobs:
  compile-stateless-validator:
    name: Compile ${{ matrix.el }}/${{ matrix.zkvm }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Reth
          - el: reth
            zkvm: airbender
          - el: reth
            zkvm: openvm
          - el: reth
            zkvm: pico
          - el: reth
            zkvm: risc0
          - el: reth
            zkvm: sp1
          - el: reth
            zkvm: zisk
          # Ethrex
          - el: ethrex
            zkvm: risc0
          - el: ethrex
            zkvm: sp1
          - el: ethrex
            zkvm: zisk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Pull compiler image
        run: |
          docker pull ghcr.io/eth-act/ere/ere-compiler-${{ matrix.zkvm }}:${ERE_TAG}

      - name: Apply zkVM patch
        run: |
          cargo run -p xtask -- ${{ matrix.zkvm }}

      - name: Compile guest
        run: |
          docker run \
            -v ./ere-guests:/guest \
            -v ./output:/output \
            ghcr.io/eth-act/ere/ere-compiler-${{ matrix.zkvm }}:${ERE_TAG} \
            --compiler-kind rust-customized \
            --guest-path /guest/stateless-validator/${{ matrix.el }}/${{ matrix.zkvm }} \
            --output-path output/${{ matrix.el }}-${{ matrix.zkvm }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.el }}-${{ matrix.zkvm }}
          path: output/${{ matrix.el }}-${{ matrix.zkvm }}
          if-no-files-found: error

  create-release:
    name: Create release
    needs: compile-stateless-validator
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Rlease
        uses: softprops/action-gh-release@v2
        with:
          name: Compiled Guests (${{ github.ref_name }})
          files: artifacts/*
          body: |
            This release contains compiled guest programs for various zkVMs.

            Built with Ere compiler version: `${{ env.ERE_TAG }}`.

            ## Compiled guest programs

            ### Reth stateless validator

            - [`reth-airbender`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/reth-airbender)
            - [`reth-openvm`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/reth-openvm)
            - [`reth-pico`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/reth-pico)
            - [`reth-risc0`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/reth-risc0)
            - [`reth-sp1`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/reth-sp1)
            - [`reth-zisk`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/reth-zisk)

            ### Ethrex stateless validator

            - [`ethrex-risc0`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/ethrex-risc0)
            - [`ethrex-sp1`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/ethrex-sp1)
            - [`ethrex-zisk`](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/ethrex-zisk)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
